* pdf-tools
probably best available for emacs in terms of pdf.
https://github.com/politza/pdf-tools

it requires some work to make it work on mac, easier on Linux.
- install the package *pdf-tools* in emacs
- load it by adding ~(require 'pdf-tools)~ in the init file
- parepare dependencies for pdf-tools
#+BEGIN_SRC bash
brew install poppler automake
brew install zlib
#+END_SRC

then change *PKG_CONFIG_PATH* since zlib is installed at different location
(adjust according to zlib version):
#+BEGIN_SRC bash
export PKG_CONFIG_PATH=/usr/local/Cellar/zlib/1.2.11/lib/pkgconfig:/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
#+END_SRC
- restart emacs, then run ~pdf-tools-install~ from emacs

tested on macOS High Sierra with emacs 26

** more issue
for some reason, after I restarted emacs and open a pdf file, it appered in a fundamental mode,
not pdf-view mode.

a bit googling showed that I need to add this to my init file:
#+BEGIN_SRC elisp
(pdf-tools-install)
#+END_SRC

however this triggered a error which I have no idea why..
but albeit the error, open pdf file works now so I have to put
this at last so it won't stop other config.

* integrate with org-mode
out of the box, org mode won't work with pdf tools, need some setup. [fn:1] [fn:3]

** org-pdfview
- install ~org-pdfview~ package [fn:2].
for some reason, doom-emacs can't install it successfully, so I ended up have to
make a copy of ~org-pdfview.el~ in my config directory, and make sure it loads first
- then configure it:
#+BEGIN_SRC elisp
(eval-after-load 'org '(require 'org-pdfview))

(add-to-list 'org-file-apps
             '("\\.pdf\\'" . (lambda (file link)
                                     (org-pdfview-open link))))
#+END_SRC
- finally use it in org mode with link like:
#+BEGIN_EXAMPLE
[[pdfview:/path/to/myfile.pdf::42][My file Description]]
#+END_EXAMPLE

** pdf-tools-org
main features are importing and exporting pdf annotations from/to org files

config:
#+begin_src emacs-lisp
;;auto save org when pdf file closed
(add-hook 'after-save-hook
     (lambda ()
       (when (eq major-mode 'pdf-view-mode) (pdf-tools-org-export-to-org-mod))))
#+end_src
* keybinding and integrate with Evil
pretty much came from here [fn:5] but I modified it a bit using ~general.el~

[fn:1] https://emacs.stackexchange.com/questions/19686/how-to-use-pdf-tools-pdf-view-mode-in-emacs
[fn:2] https://github.com/markus1189/org-pdfview/blob/master/org-pdfview.el
[fn:3] http://tech.memoryimprintstudio.com/pdf-annotation-related-tools/
[fn:4] https://github.com/pinguim06/pdf-tools-org
[fn:5] https://github.com/noctuid/evil-guide
